[server]
address = "127.0.0.1"
port = 8501
headless = true
maxUploadSize = 80

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#047E4A"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F5F4"
textColor = "#202724"
font = "sans serif"
